-- Public /episodes archive (Spot-challenge history + live Subotto stub)
CREATE TABLE IF NOT EXISTS episodes (
    number INTEGER PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    heading TEXT NOT NULL DEFAULT '',
    submissions_count INTEGER,
    winner_name TEXT NOT NULL DEFAULT '',
    winner_video_id TEXT NOT NULL DEFAULT '',
    challenge_playlist_id TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    rows TEXT NOT NULL DEFAULT '[]'
);

INSERT OR IGNORE INTO episodes (number, title, heading, submissions_count, winner_name, winner_video_id, challenge_playlist_id, note, rows) VALUES
(19, 'Insurance Agency', '', 10, 'Smolin', 'jmRgohBsm-g', 'PLckiUs3F1znI', '', '[{"kind":"full","label":"Full Episode","url":"https://youtu.be/bIP51Oyfc2U"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLckiUs3F1znI"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=jmRgohBsm-g"},{"kind":"trick","label":"Trick of the show","url":"https://www.twitch.tv/tew020/clip/FunInspiringRadishSwiftRage-gS1Busrm98hEUbJX"}]'),
(18, 'Underground Parking Lot', '', 18, 'Khorne', 'cnQRE4n-McQ', 'PLYFuGvbCwJnc', '', '[{"kind":"full","label":"Full Episode","url":"https://youtu.be/n1mBIXDAUZE"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLYFuGvbCwJnc"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=cnQRE4n-McQ"},{"kind":"trick","label":"Trick of the show","url":"https://www.twitch.tv/tew020/clip/FaithfulGleamingBisonWutFace-t-Z2s4Yr53dTvFYw"}]'),
(17, 'Stalin Plaza', '', 14, 'BookerTBags', 'gkgPWw8kaKk', 'PLSMUhDYLKe8M', '', '[{"kind":"full","label":"Full Episode","url":"https://youtu.be/GvUUca5EuLs"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLSMUhDYLKe8M"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=gkgPWw8kaKk"}]'),
(16, 'West Paris', '', 12, 'Vers & ZaRaz', 'CG_g6Ug4O5E', 'PLY0i3Jb43cQM', '', '[{"kind":"full","label":"Full Episode","url":"https://youtu.be/rXbTJs6W_x8"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLY0i3Jb43cQM"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=CG_g6Ug4O5E"}]'),
(15, 'Chatham Towers', '', 19, 'beefparcel', 'd7dUimedVLc', 'PLPAJiFyzqvAk', '', '[{"kind":"full","label":"Full Episode","url":"https://youtu.be/3fFhZpj8n30"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLPAJiFyzqvAk"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=d7dUimedVLc"}]'),
(14, 'Pyramid Ledges + Hangover Square', 'EP14 Pyramid Hangover', 9, 'BookerTBags', 'Req7qPhH7Ts', 'PLf1sSxWZR8BVz2eaPtTjLg2KwUdH_kCgb', '', '[{"kind":"full","label":"Full Episode","url":"https://youtu.be/hx0iW3IO6dM"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLf1sSxWZR8BVz2eaPtTjLg2KwUdH_kCgb"},{"kind":"winner","label":"Winner","url":"https://youtu.be/Req7qPhH7Ts"}]'),
(13, 'Federal Plaza', 'EP13 Fed Plaza', 14, 'Mad Digital', 'xsaj_U-DxLA', 'PLf1sSxWZR8BWbJbiGAsujKZRlWtXoE4Gk', '', '[{"kind":"full","label":"Full Episode","url":"https://youtu.be/N3UqdoXF1hw"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLf1sSxWZR8BWbJbiGAsujKZRlWtXoE4Gk"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=xsaj_U-DxLA"}]'),
(12, 'Police Underpass', '', 11, 'Khorne', 'FaexEO_dRQE', 'PLf1sSxWZR8BV0UhbRHrxNET4S_iMO9Qe-', '', '[{"kind":"full","label":"Full Episode","url":"https://www.youtube.com/watch?v=xmnujVQc2a4"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLf1sSxWZR8BV0UhbRHrxNET4S_iMO9Qe-"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=FaexEO_dRQE"}]'),
(11, 'Hangar of the Finest', '', 11, 'ZaRaz', '8LHc51PZAMY', 'PLf1sSxWZR8BXnUp96YasGgj96JU8Sw-tS', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=01b-p96Mu5U"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BXnUp96YasGgj96JU8Sw-tS"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=8LHc51PZAMY"}]'),
(10, 'Highline Bridge 2', '', 11, 'DrGM', 'I-9WTJaq-eA', 'PLf1sSxWZR8BXXJf5AmtHFA6PSdDeHLcMf', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=GTbEoJeanMQ"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BXXJf5AmtHFA6PSdDeHLcMf"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=I-9WTJaq-eA"}]'),
(9, 'El Lay', '', 10, 'Sisterfister', 'N-LsdyQZxPY', 'PLf1sSxWZR8BU8ZklmF1XjV1L1FKwFXbob', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=CL28X3YUlx4"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BU8ZklmF1XjV1L1FKwFXbob"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=N-LsdyQZxPY"}]'),
(8, 'Philly Underground', '', 9, 'EaSkateVideo', 'SOE2z0pvnmA', 'PLf1sSxWZR8BUA0tBXVgfo8KNw97QaoUW_', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=aYlcBZEacXA"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BUA0tBXVgfo8KNw97QaoUW_"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=SOE2z0pvnmA"}]'),
(7, 'Muni', '', 13, 'ZaRaz', 'cKaAtZg8ASI', 'PLf1sSxWZR8BWB7PO5DHFb4YzExpnGJThP', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=3_LZdJAD1aI"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BWB7PO5DHFb4YzExpnGJThP"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=cKaAtZg8ASI"}]'),
(6, 'Schoolyard', '', 7, 'Alix', 's3YxHgoxAfQ', 'PLf1sSxWZR8BXcrr2w7VWnBAp_r5AFvojQ', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=RHZQy35LbPY"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BXcrr2w7VWnBAp_r5AFvojQ"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=s3YxHgoxAfQ"}]'),
(5, 'crea-ture Waterpark', '', 10, 'Krown', '7_s0B04UQpU', 'PLf1sSxWZR8BXVrQMBhF5MvEh2aHGkT_y_', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=ZZvt7Ovj-OU"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BXVrQMBhF5MvEh2aHGkT_y_"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=7_s0B04UQpU"}]'),
(4, 'LES Coleman Park', '', 12, 'Twicekillah', 'WOi9VCGFjkE', 'PLf1sSxWZR8BUzAl93IFF36UHVRqWA6aBu', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=j_VcwJqpklk"},{"kind":"playlist","label":"Submissions Playlist","url":"https://youtube.com/playlist?list=PLf1sSxWZR8BUzAl93IFF36UHVRqWA6aBu"},{"kind":"winner","label":"Winner","url":"https://youtube.com/watch?v=WOi9VCGFjkE"}]'),
(3, 'Phat Nugget Mall', '', 15, 'Llamuhs', '3cLTPVcaO8g', 'PLf1sSxWZR8BWVEi5dBV7PtM_j6bbakxbG', '', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=3NV5WbQUizU"},{"kind":"playlist","label":"Submissions Playlist","url":"https://www.youtube.com/playlist?list=PLf1sSxWZR8BWVEi5dBV7PtM_j6bbakxbG"},{"kind":"winner","label":"Winner","url":"https://www.youtube.com/watch?v=3cLTPVcaO8g"}]'),
(2, '', '', NULL, '', '', '', 'Spot challenge not yet launched.', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=8JOlhzVg95Y"}]'),
(1, 'TECHNICAL TEST VOD EP 001', 'EP1 TECHNICAL TEST VOD EP 001', NULL, '', '', '', 'Spot challenge not yet launched.', '[{"kind":"full","label":"Full Episode","url":"https://youtube.com/watch?v=ZgNXBz0_eJo"}]');
