ALTER TABLE skater_profiles ADD COLUMN avatar_r1 INTEGER NOT NULL DEFAULT 50;
ALTER TABLE skater_profiles ADD COLUMN avatar_r2 INTEGER NOT NULL DEFAULT 50;
ALTER TABLE skater_profiles ADD COLUMN avatar_r3 INTEGER NOT NULL DEFAULT 50;
ALTER TABLE skater_profiles ADD COLUMN avatar_r4 INTEGER NOT NULL DEFAULT 50;
ALTER TABLE skater_profiles ADD COLUMN avatar_border INTEGER NOT NULL DEFAULT 0;
